#!/usr/bin/env bash
# Writes Reflex/SpotifySecrets.swift from SPOTIFY_CLIENT_ID.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/Reflex/SpotifySecrets.swift"
CLIENT_ID="${SPOTIFY_CLIENT_ID:-}"

python3 - "$OUT" "$CLIENT_ID" <<'PY'
import sys

path, client_id = sys.argv[1], sys.argv[2]
escaped = client_id.replace("\\", "\\\\").replace("\"", "\\\"")
content = f"""// Auto-generated by Scripts/generate-spotify-secrets.sh — do not edit.
enum SpotifySecrets {{
    static let clientID = "{escaped}"
}}
"""
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
PY
