import Foundation
import PackagePlugin

/// SwiftPM build-tool plugin that generates `SpotifySecrets.swift` from the
/// `SPOTIFY_CLIENT_ID` environment variable at build time. The value is baked
/// into the resulting binary.
///
/// Missing env var is tolerated — the generated file will hold an empty
/// string, and `SpotifyAuthManager.isConfigured` surfaces a clean UI state.
@main
struct GenerateSpotifySecretsPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let env = ProcessInfo.processInfo.environment
        let clientID = env["SPOTIFY_CLIENT_ID"] ?? ""

        let outputDir = context.pluginWorkDirectory
        let outputFile = outputDir.appending("SpotifySecrets.swift")

        let content = """
        // Auto-generated by GenerateSpotifySecrets build plugin. Do not edit.
        enum SpotifySecrets {
            static let clientID = "\(clientID)"
        }

        """

        return [
            .prebuildCommand(
                displayName: "Generate SpotifySecrets.swift",
                executable: Path("/bin/sh"),
                arguments: [
                    "-c",
                    "printf '%s' \"$1\" > \"$2\"",
                    "sh",
                    content,
                    outputFile.string
                ],
                outputFilesDirectory: outputDir
            )
        ]
    }
}
